### ISSUE TITLE
Question re PyObject_Del() being converted to PyObject_Free()

### ISSUE THREAD

**Issue by lazka** [python/pythoncapi-compat#103]
The upgrade script replaces the following call to PyObject_Del() with PyObject_Free() here: https://github.com/pygobject/pycairo/blob/ce6118526606f93d3132f881bf548ce746b782fe/cairo/path.c#L242 and it seems deliberate (??)

PyObject_Del() is documented to be used for PyObject_New() or PyObject_NewVar(), while PyObject_Free() is documented to be used for PyObject_Malloc(), PyObject_Realloc() or PyObject_Calloc(), otherwise it is undefined behavior.

* https://docs.python.org/3.14/c-api/memory.html#c.PyObject_Free
* https://docs.python.org/3.14/c-api/allocation.html#c.PyObject_Del

I'm a bit confused by this.

**Comment by vstinner** [comment]
PyObject_Del() is just a deprecated alias to PyObject_Free():

`#define PyObject_Del            PyObject_Free`

src: https://github.com/python/cpython/blob/3b034d26eb8480f8d12ae11f42d038d24cf8498a/Include/objimpl.h#L107

I agree that it's confusing :-)

**Comment by lazka** [comment]
I see, so it's just outdated documentation.

Should I move this to CPython?

**Comment by lazka** [comment]
Hm, PyObject_Del is used all over the place in the docs, and in CPython source, with no indication that it is deprecated besides that one inline comment. So I'm wondering if it really is deprecated at all?

**Comment by vstinner** [comment]
It's just deprecated in a comment, nothing more. Maybe the upgrade script should leave them unchanged.

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/122453 for Python.

**Comment by lazka** [comment]
Thanks!
