### ISSUE TITLE
Add shims for critical section macros

### ISSUE THREAD

**Issue by ngoldbaum** [python/pythoncapi-compat#105]
https://docs.python.org/3.13/c-api/init.html#python-critical-section-api

On older pythons these can just be open and close brace.

**Comment by vstinner** [comment]
@ngoldbaum: yeah, it makes sense. Do you want to propose a PR for that?

> On older pythons these can just be open and close brace.

Or just be empty.

**Comment by vstinner** [comment]
Implemented by https://github.com/python/pythoncapi-compat/pull/106
