### ISSUE TITLE
Support PyLong_AsNativeBytes()?

### ISSUE THREAD

**Issue by skirpichev** [python/pythoncapi-compat#107]
I would guess it wasn't supported, well, for obvious reasons (complexity).

But if it's going to be used in PyLong_Export() - maybe we should revisit it?

**Comment by vstinner** [comment]
The implementation is about 186 lines. IMO it's too big and too complex for pythoncapi-compat sadly :-( The https://github.com/vstinner/deadparrot would be a better place to backport such feature.

**Comment by skirpichev** [comment]
Then maybe using PyLong_AsLongAndOverflow() is better for PyLong_Export.  I did pr to switch: https://github.com/vstinner/cpython/pull/6.  This clear practical need for backport.

**Comment by vstinner** [comment]
You shouldn't worry about pythoncapi-compat: there is a great freedom on how we can do things in pythoncapi-compat. It shouldn't impact PEP 757 design.

**Comment by skirpichev** [comment]
Sure, we could use PyLong_AsLongAndOverflow() just for backports.  But it looks faster than current solution, at least for my benchmarks.
