### ISSUE TITLE
Add "Getting Started" section to README.md

### ISSUE THREAD

**Issue by erlend-aasland** [python/pythoncapi-compat#23]
We should add a short "getting started" section to the repo README. Most people will expect to be able to find out how to apply this to their project, just by visiting the repo.

**Comment by vstinner** [comment]
Do you want to propose a PR for that? In pyperf, I wrote that:
https://github.com/psf/pyperf/blob/main/README.rst#usage

**Comment by erlend-aasland** [comment]
Yes, I'll get to it hopefully this weekend.

**Comment by vstinner** [comment]
I reorganized the documentation like that: https://pythoncapi-compat.readthedocs.io/en/latest/

Is it better? Or do you want to writ a more practical guide to use the project?

**Comment by erlend-aasland** [comment]
Sorry I haven't gotten around to fix this.

> I reorganized the documentation like that: https://pythoncapi-compat.readthedocs.io/en/latest/
>
> Is it better?

Yes, definitely!

> Or do you want to writ a more practical guide to use the project?

I would like to add a condensed version of the RTD docs to the repo README.md file so user will be able to see a quick how-to/tutorial just by visiting the repo.
