### ISSUE TITLE
Compilation breaks on AppVeyor for Python 2.7

### ISSUE THREAD

**Issue by icemac** [python/pythoncapi-compat#30]
Thank you for this repository. I successfully used the C code provided here in some packages to gain Python 3.11 compatibility.

But when I tried using `pythoncapi_compat.h` in `zope.container` it breaks on AppVeyor for Python 2.7, see https://github.com/zopefoundation/zope.container/pull/44 and https://ci.appveyor.com/project/mgedmin/zope-container/builds/43344687/job/p4m258uqhi0e99w4

Sorry, I have not enough C knowledge to debug this myself, I tinkered a bit but with no luck:

`#  define PYCAPI_COMPAT_INLINE(TYPE static __inline TYPE` looks like a syntax error to me (missing closing parenthesis). But adding it after the first `TYPE` did just produced another error when `PYCAPI_COMPAT_STATIC_INLINE` is used to define `_Py_NewRef` (See https://ci.appveyor.com/project/mgedmin/zope-container/builds/43344750/job/tod2fatoyadgi313)

Do you have any idea what I did wrong?

**Comment by vstinner** [comment]
Oh, it's a bad typo. Can you please test if https://github.com/python/pythoncapi-compat/commit/c43cea27f6558336ff5a5f602d0ea8710ae989bb fix it?

I also created https://github.com/python/pythoncapi-compat/pull/31 to add an AppVeyor CI to test Python 2.7 support on Windows.

**Comment by icemac** [comment]
@vstinner Thank you for the quick fix. Now compilation on AppVeyor passes for Python 2.7 up to 3.10.

**Comment by vstinner** [comment]
Great! Thank you for your feedback.

**Comment by vstinner** [comment]
@icemac: I failed to enable AppVeyor on this project.

I tried to build the C extensions on Windows with Python 2.7 using GitHub Action, but it also failed: https://github.com/python/pythoncapi-compat/pull/38

I give up. I think that I will try to do best effort support: if someone reports an issue, I will try to fix it. But I don't see how to easily get a CI for that on GitHub.

**Comment by icemac** [comment]
@vstinner Thank you for the effort you put into this issue. As it currently works for me I see no need to further investigate.
