### ISSUE TITLE
PyCode_GetCode is not a static inline function 

### ISSUE THREAD

**Issue by kumaraditya303** [python/pythoncapi-compat#39]
`PyCode_GetCode` is not marked with `PYCAPI_COMPAT_STATIC_INLINE` hence it causes multiple definition error during linking.

See https://github.com/python/pythoncapi-compat/blob/46d5a61f6197f8dc1ce47ad683ea3f15d4d4d4a1/pythoncapi_compat.h#L474-L480

**Comment by vstinner** [comment]
Fixed by commit 2df7eddcca3aeb83f0930267468bd56986bc6291.

Sadly, the test suite didn't notice this mistake.
