### ISSUE TITLE
Consider adding `_PyCFunction_CAST`

### ISSUE THREAD

**Issue by oraluben** [python/pythoncapi-compat#43]
Use case: now clinic.py uses `_PyCFunction_CAST`. I understand that backward compatibility isn't the first priority of clinic.py, but I think it's still good to have if possible.

**Comment by vstinner** [comment]
Hi, do you mean that you are using Argument Clinic in your 3rd party project and then expect the generated code to be usable on older Python versions?

In pythoncapi-compat, I don't want to add *private* functions. If you want it in pythoncapi-compat, you should request to get it as a public function (macro) in Python first.

Also, I suggest you to open a discussion in Python about making Argument Clinic usable outside Python and to modify it to avoid internal functions. I already looked at this and it seems doable.

Note: I'm the one who added _PyCFunction_CAST() :-) It was to help with C++ compatibility.

**Comment by oraluben** [comment]
> Hi, do you mean that you are using Argument Clinic in your 3rd party project and then expect the generated code to be usable on older Python versions?

Exactly.

> In pythoncapi-compat, I don't want to add _private_ functions. If you want it in pythoncapi-compat, you should request to get it as a public function (macro) in Python first.

That does make sense.

> Also, I suggest you to open a discussion in Python about making Argument Clinic usable outside Python and to modify it to avoid internal functions. I already looked at this and it seems doable.

Thanks, I agree that's at least worth some discussion.

> Note: I'm the one who added _PyCFunction_CAST() :-) It was to help with C++ compatibility.

: )

**Comment by oraluben** [comment]
https://discuss.python.org/t/propose-that-argument-clinic-only-uses-public-python-apis-to-make-it-easier-to-use-outside-cpython/16557/2

**Comment by erlend-aasland** [comment]
See also: python/cpython#85283
