### ISSUE TITLE
Add hollerith to users

### ISSUE THREAD

**Issue by koubaa** [python/pythoncapi-compat#47]
I recently developed a (tiny) Cython+C module that uses this. It could be useful as a minimal example.

https://github.com/pyansys/hollerith

**Comment by vstinner** [comment]
If you use Cython, you don't need pythoncapi-compat, no?

**Comment by koubaa** [comment]
@vstinner it is possible to mix cython + c in the same extension module. cython can call C code declared in header files.  The type "object" when used in a cython declaration maps to a PyObject* in C.

I needed to write some python c/api and C code directly and use cython to wrap them and interface with them. (I use cython where I can and C where I must)

**Comment by vstinner** [comment]
Well, I'm glad that it's useful to you :-)

**Comment by vstinner** [comment]
Fixed by commit 3779f1221363b0f8c65c4f0ee24b36603c98547a
