### ISSUE TITLE
`PyList_GetItemRef` implementation?

### ISSUE THREAD

**Issue by ngoldbaum** [python/pythoncapi-compat#88]
Python 3.13 adds [`PyList_GetItemRef`](https://docs.python.org/3.13/c-api/list.html#c.PyList_GetItemRef), it would be nice to have a compatibility definition for older python versions.

**Comment by vstinner** [comment]
Implemented in commit f66799130acd8843802185553dadf0e300c5fe05. Thanks for the reminder.
